### ISSUE TITLE
edu.biu.scapi.primitives.dlog.miracl.MiraclDlogECFp not Serializable 

### ISSUE THREAD

**Issue by mubeequreshi** [cryptobiu/scapi#100]
Hy,
I wanted to share elliptical curve  DlogGroup between many parties 
which is generated from the the below code
DlogGroup dlogGroup = DlogGroupFactory.getInstance().getObject("DlogECFp(P-224)","Miracl") .

I would like to send this dlgroup with my channel to other running channels but everytime it gives me not serializable exception.

I have tried different ways to serialize above DlogGroup but not able to succeed. Like I have tried to extend my class with MiraclDlogECFp and overwrite writeObject() method of Serializable interface, and also done one try with json but non of them worked for me.
Any help or suggestions in this regard will be very helpful for me .I do not know what I am missing

**Comment by moriyaw** [comment]
You can't serialize dlog object since it has a pointer to the miracl object, which locate in the current machine so you cannot "move" it to other party. (If you will send it to the other party the pointer will point some random place in memory which will end up with memory problems). Each party should create its own dlog group using the same parameters. 

What you can send is the group **element**, which has a function generateSendableData() that returns a sendable object. On the other side, use the reconstructElement() function of the DlogGroup that gets this sendable object and translates it to group element back.

**Comment by mubeequreshi** [comment]
Thank you very much for your reply.
But that will return me the group element on the other side, but how I can generate the same DlogGroup on the other side ?  I am interested to perform diffie-hellman elliptive curve with the same DlogGroup on both sides .  Like in case if I get I get the group element by using reconstructElement() function how can I perform multiplyGroupElement() on the other side? because it requires to have dlGroup object , and my only worry is that If I generate a new instance of dlGroup on the other side .I will be the new one with the new initialization or not ?

**Comment by moriyaw** [comment]
You should generate the Dlog group in both sides by the same way.
The DlogGroup is constructed with a fixed parameters (not random) so both dlog groups will be the same.

**Comment by mubeequreshi** [comment]
Thank you very much for your help. I was able to generate same dlGroup and tested my code. It worked for me.
