### ISSUE TITLE
make for SCAPI v2.4 doesn't work due to missing submodules

### ISSUE THREAD

**Issue by amaloz** [cryptobiu/scapi#82]
Grabbing v2.4 [here](https://github.com/cryptobiu/scapi/releases/tag/SCAPI-V2-4-0) and typing `make` produces the following:

```
Compiling the Crypto++ library...
cp -r lib/CryptoPP PATH/scapi-SCAPI-V2-4-0/build
make[1]: Entering directory 'PATH/scapi-SCAPI-V2-4-0/build/CryptoPP'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory 'PATH/scapi-SCAPI-V2-4-0/build/CryptoPP'
makefile:125: recipe for target 'compile-cryptopp' failed
make: *** [compile-cryptopp] Error 2
```

Cloning the latest git code and pulling the submodules fixes this problem, so it seems to be that the submodules are missing in the release.

**Comment by AsafKleinbort** [comment]
Hi,
As you can see in http://scapi.readthedocs.org/en/latest/install.html, in order to install scapi in a Linux machine you'll have to build the underlying c++ sub modules . And in order to build these modules you must pull the submodules. 
You can pull Scapi2-4 but you'll have to pull the submodules anyhow.
Hope it helps.

**Comment by amaloz** [comment]
Those instructions (as far as I can tell) say nothing about building from the release.  Maybe it'd be helpful to add a line here about that.  Thanks!
